version: "3.7"

services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8000:80
      - 443:443
    volumes:
      # Main config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/html:/var/www/html
      # Server blocks config
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  client:
    container_name: client
    build: ./client
    restart: "always"
    volumes:
      - ./client/:/opt/client/
      - /app/node_modules/
    env_file:
      - ./.dev.common.env
      - ./.dev.client.env
    ports:
      - 3000:3000 # must be the same as `PORT` in client.env
    depends_on:
      - api

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    restart: "no"
    volumes:
      # the path after `:` (i.e. `/music/`) should match the path in
      # `MUSIC_LIB_PATH` variable in `api.env`
      - /mnt/9904b8b1-2f58-4bc1-a5de-aa1584088b5e/projects/musicbox/_source/music/:/music/
      # The path in `:/opt/api` should match the path in WORKDIR in ./api/Dockerfile
      - ./api/src:/opt/api/src
      - ./api/tsconfig.json:/opt/api/tsconfig.json
    env_file:
      - ./.dev.common.env
      - ./.dev.api.env
      - ./.dev.db.env
    ports:
      # node.js process is listening for a debugging client on
      - 9229:9229
    expose:
      - 5000

  db:
    container_name: db
    image: postgres
    restart: "no"
    env_file:
      - ./.dev.db.env
    ports:
      - 54323:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./db/volume/:/var/lib/postgresql/data

networks:
  frontnet:
    driver: bridge
