version: "3.7"



services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8000:80
      - 443:443
    volumes:
      # Main config
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log/:/var/log/nginx/
      - ./nginx/html:/var/www/html
      # Server blocks config
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - client



  client:
    container_name: client
    build: ./client
    restart: "always"
    volumes:
      - ./client/:/opt/client/
      - /app/node_modules/
    env_file:
      - ./common.env
      - ./client.env
    ports:
      - 3000:3000 # must be the same as `PORT` in client.env
    depends_on:
      - api-server



  api-server:
    container_name: api-server
    build: 
      context: ./api-server
      dockerfile: Dockerfile.dev
    restart: "no"
    volumes:
      # the path after `:` (i.e. `/music/`) should match the path in
      # `MUSIC_LIB_PATH` variable in `api-server.env`
      - /mnt/9904b8b1-2f58-4bc1-a5de-aa1584088b5e/projects/musicbox/_source/music/:/music/
      # The path in `:/opt/api-server` should match the path in WORKDIR in ./api-server/Dockerfile
      #- ./api-server/src:/opt/api-server/src
      #- ./api-server/tsconfig.json:/opt/api-server/tsconfig.json
      - ./api-server/src:/opt/api-server/src
      - ./api-server/tsconfig.json:/opt/api-server/tsconfig.json
    env_file:
      - ./common.env
      - ./api-server.env
      - ./track-storage.env
    ports:
      # node.js process is listening for a debugging client on
      - 9229:9229
    expose:
      - 5000
    depends_on:
      - track-storage



  track-storage:
    container_name: track-storage
    image: postgres
    restart: "no"
    env_file:
      - ./api-server.env
      - ./track-storage.env
    ports:
      - 54323:5432
    volumes:
      - ./track-storage/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./track-storage/volume/:/var/lib/postgresql/data



networks:
  frontnet:
    driver: bridge
